FROM sagcr.azurecr.io/webmethods-edge-runtime:10.16.5
ADD --chown=sagadmin:sagadmin EdgeNL_OD_Demo /opt/softwareag/IntegrationServer/packages/EdgeNL_OD_Demo
ADD --chown=sagadmin:sagadmin OD_Demo_Utils /opt/softwareag/IntegrationServer/packages/OD_Demo_Utils