# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'wm-edge-od-demo'
  dockerRegistryServiceConnection: 'OdidoECR'
  imageRepository: 'sag-globalpresales/mihe-ecr/odido-edge'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- script: echo Run Docker
  displayName: 'Run a Docker build script'

- checkout: self
  submodules: true

- task: Docker@2
  displayName: Login to SAGCR
  inputs:
    containerRegistry: 'SoftwareAGContainers'
    command: login
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: buildAndPush
    Dockerfile: container/Dockerfile
    tags: |
      latest
      $(tag)
